import {db} from "@/lib/db";
import {hpWeightedProgress,manufacturing} from "@/lib/stats";
import {BuildingActions} from "@/components/BuildingActions";
import Link from "next/link";
export const dynamic="force-dynamic";

export default async function Search({searchParams}:{searchParams:Promise<{q?:string}>}){
 const q=(await searchParams).q?.trim()??"";
 const results=q?await db.hpBuilding.findMany({where:{isActive:true,OR:[{project:{projectId:{contains:q}}},{uavt:{contains:q}},{district:{contains:q}},{neighborhood:{contains:q}},{street:{contains:q}},{doorNumber:{contains:q}},{buildingName:{contains:q}}]},include:{project:true,notes:{orderBy:{createdAt:"desc"},take:1}},orderBy:[{project:{projectId:"asc"}},{district:"asc"},{neighborhood:"asc"}],take:1000}):[];
 const completedBuildings=results.filter(b=>manufacturing(b,b.project.projectType).percent===100),completed=completedBuildings.length,ongoing=results.filter(b=>{const n=manufacturing(b,b.project.projectType).percent;return n>0&&n<100}).length,totalHp=results.reduce((a,b)=>a+b.bbkHp,0),completedHp=completedBuildings.reduce((a,b)=>a+b.bbkHp,0),remainingHp=totalHp-completedHp,gf=results.filter(b=>b.project.projectType==="GF"),bf=results.filter(b=>b.project.projectType==="BF"),combined=totalHp?(hpWeightedProgress(gf,"GF")*gf.reduce((a,b)=>a+b.bbkHp,0)+hpWeightedProgress(bf,"BF")*bf.reduce((a,b)=>a+b.bbkHp,0))/totalHp:0,weightedHp=completed===results.length&&results.length?100:Math.min(99.9,Math.round(combined*10)/10),hpDisplay=`${completedHp} / ${totalHp}`;
 return <><div className="top"><div><h1>Global Arama</h1><div className="muted">Proje ID, UAVT, ilçe, mahalle, cadde/sokak veya bina numarası</div></div></div><form className="filters"><input name="q" defaultValue={q} placeholder="Örn: Biga Hamdibey Sanayi 17" style={{minWidth:320}}/><button>Ara</button></form>{q&&<><div className="filters"><span className="badge">Toplam: {results.length} bina</span><span className="badge">GF: {gf.length} bina</span><span className="badge">BF: {bf.length} bina</span><span className="badge">Toplam HP: {hpDisplay}</span><span className="badge ok">Tamamlanan HP: {completedHp}</span><span className="badge warn">Kalan HP: {remainingHp}</span></div><div className="table-wrap"><table><thead><tr><th>Proje ID</th><th>Tür</th><th>İlçe</th><th>Mahalle</th><th>Cadde / Sokak</th><th>Bina No</th><th>UAVT</th><th>HP</th><th>PSTN</th><th>DSL</th><th>İmalat</th><th>İlerleme</th><th>Rekor Tarihi</th><th>Son Not</th></tr></thead><tbody>{results.map(b=>{const s=manufacturing(b,b.project.projectType);return <tr key={b.id}><td><Link href={`/buildings/${b.id}`}><b>{b.project.projectId}</b></Link></td><td><span className={`badge ${b.project.projectType==="GF"?"ok":"warn"}`}>{b.project.projectType}</span></td><td>{b.district??"—"}</td><td>{b.neighborhood??"—"}</td><td>{b.street??"—"}</td><td>{b.doorNumber??"—"}</td><td>{b.uavt??"—"}</td><td>{b.bbkHp}</td><td>{b.project.projectType==="BF"?(b.pstn??"—"):"—"}</td><td>{b.project.projectType==="BF"?(b.dsl??"—"):"—"}</td><td><BuildingActions id={b.id} type={b.project.projectType} initial={{cable:b.cableCompleted,splice:b.spliceCompleted,obk:b.obkCompleted}}/></td><td><span className={`badge ${s.percent===100?"ok":s.percent?"warn":""}`}>{s.status} %{s.percent}</span></td><td>{b.rekorDate?.toLocaleDateString("tr-TR")??"Bekliyor"}</td><td title={b.notes[0]?.note}>{b.notes[0]?.note?.slice(0,50)??"—"}</td></tr>})}</tbody><tfoot><tr><th colSpan={7}>GENEL TOPLAM — Bina: {results.length} · HP: {hpDisplay} · Kalan HP: {remainingHp} · Tamamlanan Bina: {completed} · Devam Eden Bina: {ongoing}</th><th>{hpDisplay}</th><th colSpan={3}>HP Bazlı İlerleme</th><th>%{weightedHp}</th><th colSpan={2}></th></tr></tfoot></table></div></>}</>
}
