import {db} from "@/lib/db";
import {hpWeightedProgress,manufacturing} from "@/lib/stats";
export const dynamic="force-dynamic";

export default async function Dashboard(){
 const projects=await db.hpProject.findMany({include:{buildings:{where:{isActive:true}}}}),buildings=projects.flatMap(p=>p.buildings.map(b=>({...b,type:p.projectType,central:p.centralName}))),completedBuildings=buildings.filter(b=>manufacturing(b,b.type).percent===100),done=completedBuildings.length,ongoing=buildings.filter(b=>{const n=manufacturing(b,b.type).percent;return n>0&&n<100}).length,gf=buildings.filter(b=>b.type==="GF"),bf=buildings.filter(b=>b.type==="BF"),totalHp=buildings.reduce((a,b)=>a+b.bbkHp,0),completedHp=completedBuildings.reduce((a,b)=>a+b.bbkHp,0),central=new Map<string,typeof buildings>();
 for(const b of buildings){const k=b.central??"Belirsiz";central.set(k,[...(central.get(k)??[]),b])}
 const cards=[["Toplam GF Proje",projects.filter(p=>p.projectType==="GF").length],["Toplam BF Proje",projects.filter(p=>p.projectType==="BF").length],["Toplam Bina",buildings.length],["Toplam HP",`${completedHp} / ${totalHp}`],["Tamamlanan",done],["Devam Eden",ongoing],["Başlanmayan",buildings.length-done-ongoing],["Rekor",buildings.filter(b=>b.infrastructureStatus?.toLocaleLowerCase("tr")==="rekor").length]];
 return <><div className="top"><div><h1>Operasyon Dashboard</h1><div className="muted">GF ve BF saha imalatının güncel görünümü</div></div></div><div className="grid">{cards.map(([x,n])=><div className="card kpi" key={x}><span className="muted">{x}</span><strong>{n}</strong></div>)}</div><div className="grid section"><div className="card"><h2>GF İlerleme — %{hpWeightedProgress(gf,"GF")}</h2><p>Kablo bekleyen: <b>{gf.filter(x=>!x.cableCompleted).length}</b></p><p>Ek bekleyen: <b>{gf.filter(x=>!x.spliceCompleted).length}</b></p></div><div className="card"><h2>BF İlerleme — %{hpWeightedProgress(bf,"BF")}</h2><p>Kablo bekleyen: <b>{bf.filter(x=>!x.cableCompleted).length}</b></p><p>Ek bekleyen: <b>{bf.filter(x=>!x.spliceCompleted).length}</b></p><p>OBK bekleyen: <b>{bf.filter(x=>!x.obkCompleted).length}</b></p></div></div><section className="section"><h2>Santral Bazlı İlerleme</h2><div className="table-wrap"><table><thead><tr><th>Santral</th><th>Bina</th><th>HP (Biten / Toplam)</th><th>Tamamlanan</th><th>Devam Eden</th><th>HP Bazlı Yüzde</th></tr></thead><tbody>{[...central].map(([name,items])=>{const completedItems=items.filter(x=>manufacturing(x,x.type).percent===100),c=completedItems.length,o=items.filter(x=>{const n=manufacturing(x,x.type).percent;return n>0&&n<100}).length,g=items.filter(x=>x.type==="GF"),f=items.filter(x=>x.type==="BF"),hp=items.reduce((a,b)=>a+b.bbkHp,0),doneHp=completedItems.reduce((a,b)=>a+b.bbkHp,0),percent=hp?Math.round((hpWeightedProgress(g,"GF")*g.reduce((a,b)=>a+b.bbkHp,0)+hpWeightedProgress(f,"BF")*f.reduce((a,b)=>a+b.bbkHp,0))/hp):0;return <tr key={name}><td>{name}</td><td>{items.length}</td><td>{doneHp} / {hp}</td><td>{c}</td><td>{o}</td><td>%{percent}</td></tr>})}</tbody></table></div></section></>
}
