"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import type {ImportPreview} from "@/lib/hp-types";

export default function ImportForm(){
 const router=useRouter(),[preview,setPreview]=useState<ImportPreview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function inspect(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const r=await fetch("/api/import/preview",{method:"POST",body:new FormData(e.currentTarget)}),j=await r.json();r.ok?setPreview(j):setError(j.error);setBusy(false)}
 async function commit(){if(!preview)return;setBusy(true);const r=await fetch("/api/import/commit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(preview)}),j=await r.json();if(r.ok){alert("Import tamamlandı");router.push(`/projects/${preview.projectType}`)}else setError(j.error);setBusy(false)}
 const cards=preview?[["Bulunan Proje",preview.projectCount],["Kayda Alınan Proje",preview.acceptedProjects],["Kayda Alınmayan Proje",preview.rejectedProjects],["Kayda Alınan Satır",preview.acceptedRows],["Tamamlanan Satır",preview.rows.filter(row=>row.excelCompleted).length],["Kayda Alınmayan Satır",preview.rejectedRows],["Yeni Proje",preview.newProjects],["Değiştirilecek Proje",preview.replacedProjects],["Hatalı Satır",preview.errors.length]]:[];
 return <><form onSubmit={inspect} className="card"><div className="filters"><select name="projectType" required defaultValue=""><option value="" disabled>Proje türünü seçin</option><option>GF</option><option>BF</option></select><input name="file" type="file" accept=".xlsx" required/><button disabled={busy}>{busy?"Okunuyor…":"Ön İzleme Oluştur"}</button></div><small className="muted">Karar her Proje ID için bütünüyle verilir. Onaydan önce kabul ve ret nedenleri gösterilir.</small>{error&&<p className="error">{error}</p>}</form>{preview&&<div className="section"><div className="grid">{cards.map(([x,n])=><div className="card kpi" key={x}><span className="muted">{x}</span><strong>{n}</strong></div>)}</div><div className="card section"><h2>Proje Bazlı Import Kararları</h2><div className="table-wrap"><table><thead><tr><th>Proje ID</th><th>Satır</th><th>Karar</th><th>Açıklama</th></tr></thead><tbody>{preview.decisions.map(d=><tr key={d.projectId}><td><b>{d.projectId}</b></td><td>{d.rowCount}</td><td><span className={`badge ${d.accepted?"ok":"warn"}`}>{d.accepted?(d.action==="CREATE"?"Yeni kayıt":"Eski silinip yenilenecek"):"Kayda alınmayacak"}</span></td><td>{d.reason}</td></tr>)}</tbody></table></div></div>{preview.errors.length>0&&<div className="card section"><h2>Satır Hataları</h2>{preview.errors.slice(0,50).map(x=><p className="error" key={`${x.row}-${x.message}`}>Satır {x.row}: {x.message}</p>)}</div>}<p><button onClick={commit} disabled={busy||preview.acceptedProjects===0}>Kayda Alınacak Projeleri Onayla</button></p></div>}</>
}
