"use client";
import {useState} from "react";import {useRouter} from "next/navigation";import type {ProductionPreview,ProductionEntryInput} from "@/lib/production-types";
export default function ProductionUpload(){
 const router=useRouter(),[p,setP]=useState<ProductionPreview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function analyze(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const r=await fetch("/api/performance/preview",{method:"POST",body:new FormData(e.currentTarget)}),j=await r.json();r.ok?setP(j):setError(j.error);setBusy(false)}
 function ignore(index:number){if(p)setP({...p,unknown:p.unknown.filter((_,i)=>i!==index)})}
 function acceptUnknown(index:number){if(!p)return;const u=p.unknown[index],category=prompt("İmalat adı",u.text),quantity=prompt("Miktar"),unit=prompt("Birim: METRE veya ADET","METRE");if(!category||!quantity||(unit!=="METRE"&&unit!=="ADET"))return;const entry:ProductionEntryInput={teamName:u.teamName??"Bilinmeyen Ekip",category:category.toLocaleUpperCase("tr-TR"),subtype:null,cableCapacity:null,cableFamily:null,quantity:Number(quantity),unit,originalText:u.text};setP({...p,entries:[...p.entries,entry],unknown:p.unknown.filter((_,i)=>i!==index)})}
 async function commit(){if(!p)return;setBusy(true);const r=await fetch("/api/performance/commit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(p)}),j=await r.json();if(r.ok){alert("PDF performans kayıtları kaydedildi");router.push("/performance/daily")}else setError(j.error);setBusy(false)}
 const grouped=new Map<string,ProductionEntryInput[]>();if(p)for(const entry of p.entries)grouped.set(entry.teamName,[...(grouped.get(entry.teamName)??[]),entry]);
 return <><form className="card" onSubmit={analyze}><div className="filters"><input type="file" name="file" accept="application/pdf,.pdf" required/><button disabled={busy}>{busy?"Analiz ediliyor…":"PDF Analiz Et"}</button></div>{error&&<p className="error">{error}</p>}</form>{p&&<div className="section"><div className="grid">{[["Dosya",p.fileName],["Ekip",p.teams.length],["Tanınan İmalat",p.entries.length],["Tanınmayan",p.unknown.length],["Toplam Kayıt",p.entries.length]].map(([x,n])=><div className="card kpi" key={x}><span className="muted">{x}</span><strong>{n}</strong></div>)}</div><div className="card section"><label>Çalışma Tarihi <input type="date" value={p.workDate} onChange={e=>setP({...p,workDate:e.target.value})}/></label>{p.duplicate&&<p className="error"><b>Bu PDF daha önce yüklenmiş.</b></p>}</div>{[...grouped].map(([team,entries])=><div className="card section" key={team}><h2>{team}</h2>{entries.map((entry,index)=><p key={index}>{entry.subtype?`${entry.category} ${entry.subtype}`:entry.category} — <b>{entry.quantity} {entry.unit}</b></p>)}</div>)}{p.unknown.length>0&&<div className="card section"><h2>Tanınmayan Satırlar</h2>{p.unknown.map((u,index)=><div className="filters" key={`${u.text}-${index}`}><span>{u.text} <small className="muted">— {u.reason}</small></span><button type="button" className="secondary" onClick={()=>ignore(index)}>Yok Say</button><button type="button" onClick={()=>acceptUnknown(index)}>Düzenle ve Kabul Et</button></div>)}</div>}<p><button disabled={busy||p.duplicate||!p.workDate||!p.entries.length} onClick={commit}>Onayla ve Kaydet</button></p></div>}</>
}
