import {db} from "@/lib/db";
import {formatProgress,hpWeightedProgress,manufacturing} from "@/lib/stats";
import ProjectExportControls from "@/components/ProjectExportControls";
import Link from "next/link";
import {notFound} from "next/navigation";
export const dynamic="force-dynamic";
type StatusFilter="not_started"|"ongoing"|"completed";
const statusMatch=(percent:number,status:string|undefined)=>!status||(status==="not_started"?percent===0:status==="ongoing"?percent>0&&percent<100:percent===100);

export default async function Projects({params,searchParams}:{params:Promise<{type:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {type}=await params;if(type!=="GF"&&type!=="BF")notFound();const q=await searchParams,district=q.district?.trim()||undefined,status=(["not_started","ongoing","completed"].includes(q.status??"")?q.status:undefined) as StatusFilter|undefined;
 const candidates=await db.hpProject.findMany({where:{projectType:type,projectId:q.id?{contains:q.id}:undefined,projectYear:q.year?Number(q.year):undefined,buildings:district?{some:{isActive:true,district}}:undefined},include:{buildings:{where:{isActive:true}}},orderBy:{projectId:"asc"}});
 const projects=status?candidates.filter(p=>p.buildings.some(b=>(!district||b.district===district)&&statusMatch(manufacturing(b,type).percent,status))):candidates;
 const districts=await db.hpBuilding.findMany({where:{isActive:true,project:{projectType:type},district:{not:null}},select:{district:true},distinct:["district"],orderBy:{district:"asc"}});
 const rows=projects.map(p=>{const stages=p.buildings.map(b=>manufacturing(b,type)),completed=stages.filter(s=>s.percent===100).length,ongoing=stages.filter(s=>s.percent>0&&s.percent<100).length,notStarted=p.buildings.length-completed-ongoing,progress=hpWeightedProgress(p.buildings,type),completedHp=p.buildings.reduce((sum,b)=>sum+(manufacturing(b,type).percent===100?b.bbkHp:0),0);return {p,buildingCount:p.buildings.length,hp:p.buildings.reduce((a,b)=>a+b.bbkHp,0),completedHp,notStarted,ongoing,completed,progress}});
 const allBuildings=projects.flatMap(p=>p.buildings),totalHp=rows.reduce((a,r)=>a+r.hp,0),completedHp=rows.reduce((a,r)=>a+r.completedHp,0),total={buildings:rows.reduce((a,r)=>a+r.buildingCount,0),hp:`${completedHp} / ${totalHp}`,notStarted:rows.reduce((a,r)=>a+r.notStarted,0),ongoing:rows.reduce((a,r)=>a+r.ongoing,0),completed:rows.reduce((a,r)=>a+r.completed,0)},totalProgress=hpWeightedProgress(allBuildings,type);
 const filters={id:q.id,year:q.year,district,status};
 return <><div className="top"><div><h1>{type} Projeleri</h1><div className="muted">Her Proje ID yüzdesi, ID'ye bağlı tüm binaların HP miktarı üzerinden hesaplanır</div></div></div><form className="filters"><input name="id" placeholder="Proje ID" defaultValue={q.id}/><input name="year" placeholder="Yıl" defaultValue={q.year}/><select name="district" defaultValue={district??""}><option value="">Tüm ilçeler</option>{districts.map(x=>x.district&&<option key={x.district} value={x.district}>{x.district}</option>)}</select><select name="status" defaultValue={status??""}><option value="">Tüm durumlar</option><option value="ongoing">Devam Eden</option><option value="not_started">Başlamayan</option><option value="completed">Tamamlanan</option></select><button>Filtrele</button></form><ProjectExportControls type={type} filters={filters}/><div className="table-wrap"><table><thead><tr><th>Proje ID</th><th>Santral</th><th>İlçe</th><th>Yıl</th><th>Bina</th><th>HP</th><th>Başlanmayan</th><th>Devam</th><th>Tamam</th><th>HP Bazlı İlerleme</th></tr></thead><tbody>{rows.map(({p,...r})=><tr key={p.id}><td><Link href={`/projects/${type}/${p.id}`}><b>{p.projectId}</b></Link></td><td>{p.centralName??"—"}</td><td>{[...new Set(p.buildings.map(b=>b.district).filter(Boolean))].join(", ")||"—"}</td><td>{p.projectYear??"—"}</td><td>{r.buildingCount}</td><td>{r.hp}</td><td>{r.notStarted}</td><td>{r.ongoing}</td><td>{r.completed}</td><td><div className="progress"><i style={{width:`${r.progress}%`}}/></div> %{formatProgress(r.progress)}</td></tr>)}</tbody><tfoot><tr><th colSpan={4}>GENEL TOPLAM</th><th>{total.buildings}</th><th>{total.hp}</th><th>{total.notStarted}</th><th>{total.ongoing}</th><th>{total.completed}</th><th>%{formatProgress(totalProgress)}</th></tr></tfoot></table></div></>
}
