import {db} from "@/lib/db";
import {requireUser} from "@/lib/auth";
import {formatProgress,hpWeightedProgress,manufacturing} from "@/lib/stats";
import * as XLSX from "xlsx-js-style";
import PDFDocument from "pdfkit";
import path from "node:path";
import fs from "node:fs";

export const dynamic="force-dynamic";
type ProjectRow={projectId:string;central:string;districts:string;year:number|string;buildings:number;hp:number;completedHp:number;notStarted:number;ongoing:number;completed:number;progress:number;description:string};
const columns=["Proje ID","Santral","İlçeler","Yıl","Bina","HP","Başlanmayan","Devam","Tamam","HP Bazlı İlerleme","Açıklama"];

export async function GET(request:Request,{params}:{params:Promise<{type:string}>}){
 try{
  await requireUser(request);const {type}=await params;if(type!=="GF"&&type!=="BF")return Response.json({error:"Proje türü geçersiz"},{status:400});const url=new URL(request.url),format=url.searchParams.get("format"),district=url.searchParams.get("district")?.trim()||undefined,id=url.searchParams.get("id")?.trim()||undefined,year=url.searchParams.get("year")?.trim()||undefined,status=url.searchParams.get("status")?.trim()||undefined;if(format!=="xlsx"&&format!=="pdf")return Response.json({error:"Format xlsx veya pdf olmalıdır"},{status:400});
  const candidates=await db.hpProject.findMany({where:{projectType:type,projectId:id?{contains:id}:undefined,projectYear:year?Number(year):undefined,buildings:district?{some:{isActive:true,district}}:undefined},include:{buildings:{where:{isActive:true},include:{notes:{select:{note:true},orderBy:{createdAt:"desc"}}}}},orderBy:{projectId:"asc"}}),projects=status?candidates.filter(p=>p.buildings.some(b=>(!district||b.district===district)&&(status==="completed"?manufacturing(b,type).percent===100:status==="not_started"?manufacturing(b,type).percent===0:status==="ongoing"?manufacturing(b,type).percent>0&&manufacturing(b,type).percent<100:true))):candidates;
  const rows:ProjectRow[]=projects.map(p=>{const stages=p.buildings.map(b=>manufacturing(b,type));return {projectId:p.projectId,central:p.centralName??"—",districts:[...new Set(p.buildings.map(b=>b.district).filter(Boolean))].join(", ")||"—",year:p.projectYear??"—",buildings:p.buildings.length,hp:p.buildings.reduce((sum,b)=>sum+b.bbkHp,0),completedHp:p.buildings.reduce((sum,b)=>sum+(manufacturing(b,type).percent===100?b.bbkHp:0),0),notStarted:stages.filter(s=>s.percent===0).length,ongoing:stages.filter(s=>s.percent>0&&s.percent<100).length,completed:stages.filter(s=>s.percent===100).length,progress:hpWeightedProgress(p.buildings,type),description:p.buildings.flatMap(b=>b.notes.map(n=>`${b.neighborhood??"Bina"} ${b.doorNumber??""}: ${n.note}`)).join(" | ")}});
  const suffix=district?`-${safeName(district)}`:"",baseName=`${type}-Proje-ID-Listesi${suffix}-${fileStamp()}`;return format==="xlsx"?excelResponse(rows,type,baseName):pdfResponse(rows,type,district,baseName);
 }catch(e){return Response.json({error:e instanceof Error?e.message:"Proje çıktısı oluşturulamadı"},{status:400})}
}

function excelResponse(rows:ProjectRow[],type:string,baseName:string){const data:Array<Record<string,string|number>>=rows.map(toRecord);data.push({"Proje ID":`GENEL TOPLAM (${rows.length} PROJE)`,"Santral":"","İlçeler":"","Yıl":"","Bina":sum(rows,"buildings"),"HP":hpTotal(rows),"Başlanmayan":sum(rows,"notStarted"),"Devam":sum(rows,"ongoing"),"Tamam":sum(rows,"completed"),"HP Bazlı İlerleme":overall(rows),"Açıklama":""});const sheet=XLSX.utils.json_to_sheet(data),book=XLSX.utils.book_new();sheet["!cols"]=[{wch:16},{wch:22},{wch:28},{wch:9},{wch:10},{wch:14},{wch:14},{wch:10},{wch:10},{wch:18},{wch:55}];const totalStyle={fill:{patternType:"solid",fgColor:{rgb:"D9EAF7"}},font:{bold:true,color:{rgb:"17212B"}}};styleRow(sheet,rows.length+1,totalStyle);XLSX.utils.book_append_sheet(book,sheet,`${type} Proje ID Listesi`);return fileResponse(XLSX.write(book,{type:"buffer",bookType:"xlsx"}),`${baseName}.xlsx`,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")}

async function pdfResponse(rows:ProjectRow[],type:string,district:string|undefined,baseName:string){
 const doc=new PDFDocument({size:"A4",layout:"portrait",margin:18}),chunks:Buffer[]=[];doc.on("data",c=>chunks.push(c));const done=new Promise<Buffer>((resolve,reject)=>{doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject)}),font=path.join(process.env.WINDIR??"C:\\Windows","Fonts","arial.ttf");if(fs.existsSync(font))doc.font(font);const widths=[45,55,60,25,30,45,50,35,35,55,124],tableWidth=559,header=()=>{doc.fontSize(15).fillColor("#17212B").text(`${type} PROJE / ID LİSTESİ`,{align:"center"});doc.fontSize(8).text(district?`İlçe filtresi: ${district} — yüzdeler tüm proje binalarına aittir`:"Tüm projeler",{align:"center"});doc.moveDown(.5)};header();
 const draw=(values:(string|number)[],options:{header?:boolean;total?:boolean}={})=>{const h=options.header?40:50;if(doc.y+h>824){doc.addPage();header();draw(columns,{header:true})}const y=doc.y;if(options.total)doc.save().fillColor("#D9EAF7").rect(18,y,tableWidth,h).fill().restore();doc.save().lineWidth(1).strokeColor("#52606D").rect(18,y,tableWidth,h).stroke();let gx=18;for(const w of widths.slice(0,-1)){gx+=w;doc.moveTo(gx,y).lineTo(gx,y+h)}doc.stroke().restore();let x=18;doc.fillColor("#17212B").fontSize(options.header?7:7.5);values.forEach((v,i)=>{doc.text(String(v||"—"),x+2,y+4,{width:widths[i]-4,height:h-8,ellipsis:true,lineGap:1});x+=widths[i]});doc.y=y+h};draw(columns,{header:true});rows.forEach(r=>draw(Object.values(toRecord(r))));draw([`TOPLAM ${rows.length}`,"","","",sum(rows,"buildings"),hpTotal(rows),sum(rows,"notStarted"),sum(rows,"ongoing"),sum(rows,"completed"),overall(rows),""],{total:true});doc.end();return fileResponse(await done,`${baseName}.pdf`,"application/pdf")
}

function toRecord(r:ProjectRow){return {"Proje ID":r.projectId,"Santral":r.central,"İlçeler":r.districts,"Yıl":r.year,"Bina":r.buildings,"HP":r.hp,"Başlanmayan":r.notStarted,"Devam":r.ongoing,"Tamam":r.completed,"HP Bazlı İlerleme":`%${formatProgress(r.progress)}`,"Açıklama":r.description}}
function overall(rows:ProjectRow[]){const hp=sum(rows,"hp");return hp?`%${formatProgress(rows.reduce((n,r)=>n+r.hp*r.progress,0)/hp)}`:"%0.0"}
function hpTotal(rows:ProjectRow[]){return `${sum(rows,"completedHp")} / ${sum(rows,"hp")}`}
function sum(rows:ProjectRow[],key:"buildings"|"hp"|"completedHp"|"notStarted"|"ongoing"|"completed"){return rows.reduce((n,r)=>n+r[key],0)}
function styleRow(sheet:XLSX.WorkSheet,row:number,style:object){for(let col=0;col<columns.length;col++){const address=XLSX.utils.encode_cell({r:row,c:col});if(sheet[address])sheet[address].s=style}}
function fileStamp(){const p=new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).formatToParts(new Date()),v=(t:string)=>p.find(x=>x.type===t)?.value;return `${v("year")}-${v("month")}-${v("day")}_${v("hour")}-${v("minute")}-${v("second")}`}
function safeName(value:string){return value.normalize("NFKD").replace(/[^a-zA-Z0-9_-]+/g,"-").replace(/^-|-$/g,"")||"ilce"}
function fileResponse(data:Buffer,name:string,type:string){return new Response(new Uint8Array(data),{headers:{"Content-Type":type,"Content-Disposition":`attachment; filename=\"${name}\"`,"Cache-Control":"no-store"}})}
